version: "3"
services:
  postgres_warehouse:
    image: postgres
    environment:
      POSTGRES_USER: feleciap
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    networks:
      - warehouse_network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_warehouse
    networks:
      - warehouse_network

networks:
  warehouse_network:
    driver: bridge
