version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: feleciap
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    networks:
      - warehouse_network

  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - warehouse_network

networks:
  warehouse_network:
    driver: bridge
